### PR TITLE
Support React 18

### LINKED ISSUE #10: Project does not work with React 18
This package has a peer dependency on React 17, which means it breaks with React >= 18. I haven't dug deepy into the code, but perhaps it can be fixed simply by updating the package.json?

### PR DESCRIPTION
**Pull request by igitur**
Hi,

This PR is quite simple. It just upgrades the React dependency to v18. I tested it with the example project as well as my own React app. No problems.

Fixes #10

### CODE REVIEW

**Comment by mirkolenz** [comment]
I would really appreciate if this could be merged 😄

@igitur One minor note: Maybe you could set the react peer dependency to `^17.0.0 || ^18.0.0` s.t. the library can still be used for projects working with react 17.

**Comment by igitur** [comment]
> I would really appreciate if this could be merged 😄
> 
> @igitur One minor note: Maybe you could set the react peer dependency to `^17.0.0 || ^18.0.0` s.t. the library can still be used for projects working with react 17.

OK, I'll do that.

**Comment by CagriAldemir** [comment]
@igitur hi. I want to develop the library, but I can't spare time due to my workload. If you wish, I would like to add you as a developer to the project.

**Comment by igitur** [comment]
@CagriAldemir Sure, I'll help out. Through I don't think there's much to be done on this library except keep it in sync with React versions. Functionally it should be quite stable going forward.

**Comment by CagriAldemir** [comment]
Hi @igitur Finally I released a new version with version number 0.1.7
I added react@18 support. You can use the new version. Please read the doc before use.

**Pull request closed without merging**
